name: CodeChat Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get package version
      id: get_version
      run: echo "::set-output name=version::$(jq -r .version package.json)"

    - name: Debug Pre-Build Information
      run: |
        docker run --rm node:latest node -v
        docker run --rm node:latest npm -v
        docker run --rm node:latest git --version

    - name: Build and tag Docker image
      run: |
        docker build . --file Dockerfile --tag hypersender/whatsapp-api:${{ steps.get_version.outputs.version }}
        docker tag hypersender/whatsapp-api:${{ steps.get_version.outputs.version }} hypersender/whatsapp-api:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push  hypersender/whatsapp-api:latest
